name: my_gaussian_grouping
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - git
  - plyfile
  - python=3.10
  - pip
  - pytorch==2.1.2
  - torchvision==0.16.2
  - torchaudio==2.1.2
  - pytorch-cuda=12.1
  - tqdm
  - pip:
    - xformers==v0.0.23.post1
    - numpy==1.26.4
    - setuptools<70.0.0
    - opencv-python==4.10.0.84
    - joblib
    - scipy
    - wandb
    - scikit-learn
    - lpips
